### ISSUE TITLE
Add `percentile` PPL command

### ISSUE THREAD

**Issue by anasalkouz** [opensearch-project/opensearch-spark#482]
This is part of the `stats` command with specific [`percentile` parameter ](https://github.com/opensearch-project/sql/blob/7e73f124e2dc63a69750c8034558d6870c46ccf9/docs/user/ppl/cmd/stats.rst#percentile-or-percentile-approx)

**Comment by salyh** [comment]
percentile works very similar to the other, already implemented aggregate function like count etc. We just need to pass a integer literal as parameter for "percent".

I prepared a working prototype https://github.com/eliatra/opensearch-spark/commit/13b797389c0ebaf7f12112904b14e195e001c476

Although not sure how to parse the literal argument in AggregatorTranslator in a better way instead of nasty casting etc.
Any ideas @YANG-DB ?

@YANG-DB @anasalkouz If it looks good for you I am happy to prepare a PR

**Comment by YANG-DB** [comment]
thanks @salyh 
please submit a PR and we'll discuss the details over there ...
